2020-10-29 14:09:54,456 - cpblog - ERROR - Exception on /videos/ [GET]
Traceback (most recent call last):
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cp/cpdotgithub/private-website/cpblog/blueprints/video.py", line 8, in index
    return render_template('videos/index.html')
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 2, in top-level template code
    {% from 'bootstrap/pagination.html' import render_pager %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/base.html", line 106, in top-level template code
    {% block content %}{% endblock content %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 10, in block "content"
    {% include 'vedios/_vedios.html' %}
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: vedios/_vedios.html
2020-10-29 14:45:58,299 - cpblog - ERROR - Exception on /videos/ [GET]
Traceback (most recent call last):
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cp/cpdotgithub/private-website/cpblog/blueprints/video.py", line 8, in index
    return render_template('videos/index.html')
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 2, in top-level template code
    {% from 'bootstrap/pagination.html' import render_pager %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/base.html", line 106, in top-level template code
    {% block content %}{% endblock content %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 10, in block "content"
    {% include 'vedios/_vedios.html' %}
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: vedios/_vedios.html
2020-10-29 14:46:57,570 - cpblog - ERROR - Exception on /videos/ [GET]
Traceback (most recent call last):
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cp/cpdotgithub/private-website/cpblog/blueprints/video.py", line 8, in index
    return render_template('videos/video.html')
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 2, in top-level template code
    {% from 'bootstrap/pagination.html' import render_pager %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/base.html", line 106, in top-level template code
    {% block content %}{% endblock content %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 10, in block "content"
    {% include 'vedios/_vedios.html' %}
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: vedios/_vedios.html
2020-10-29 14:46:59,367 - cpblog - ERROR - Exception on /videos/ [GET]
Traceback (most recent call last):
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cp/cpdotgithub/private-website/cpblog/blueprints/video.py", line 8, in index
    return render_template('videos/video.html')
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 2, in top-level template code
    {% from 'bootstrap/pagination.html' import render_pager %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/base.html", line 106, in top-level template code
    {% block content %}{% endblock content %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 10, in block "content"
    {% include 'vedios/_vedios.html' %}
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: vedios/_vedios.html
2020-10-29 14:48:04,140 - cpblog - ERROR - Exception on /videos/ [GET]
Traceback (most recent call last):
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cp/cpdotgithub/private-website/cpblog/blueprints/video.py", line 8, in index
    return render_template('videos/video.html')
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 2, in top-level template code
    {% from 'bootstrap/pagination.html' import render_pager %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/base.html", line 106, in top-level template code
    {% block content %}{% endblock content %}
  File "/home/cp/cpdotgithub/private-website/cpblog/templates/videos/index.html", line 10, in block "content"
    {% include 'vedios/_vedios.html' %}
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/cp/cpdotgithub/private-website/.venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: vedios/_vedios.html
